nannytruffas_back/src/br/com/nannytruffas/model/Compra.java
package br.com.nannytruffas.model;

import java.util.Calendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class Compra {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)//auto incremente
	@Column(name="compra_id")
	private Integer id;
	private Calendar data = Calendar.getInstance();
	private Double preco_total;
	
	public Integer getId() {
		return id;
	}
	
	public void setId(Integer id) {
		this.id = id;
	}
	public Calendar getData() {
		return data;
	}
	public void setData(Calendar data) {
		this.data = data;
	}
	public Double getPreco_total() {
		return preco_total;
	}
	public void setPreco_total(Double preco_total) {
		this.preco_total = preco_total;
	}
	
}

nannytruffas_back/src/br/com/nannytruffas/model/Feedback.java
package br.com.nannytruffas.model;
import java.util.Calendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Feedback {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)//auto incremente
	@Column(name="feed_id")
	private Integer id;
	private String email;
	private String mensagem;
	
	@Temporal(TemporalType.DATE)
	private Calendar data_publicacao = Calendar.getInstance();
	
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getMensagem() {
		return mensagem;
	}
	public void setMensagem(String mensagem) {
		this.mensagem = mensagem;
	}
	public Calendar getData_publicacao() {
		return data_publicacao;
	}
	public void setData_publicacao(Calendar data_publicacao) {
		this.data_publicacao = data_publicacao;
	}
	
	
	
	
}

nannytruffas_back/src/br/com/nannytruffas/model/Imagens.java
package br.com.nannytruffas.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


@Entity
public class Imagens {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)//auto incremente
	private Integer id;
	private String imagem;
	private String descricao;
	
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getImagem() {
		return imagem;
	}
	public void setImagem(String imagem) {
		this.imagem = imagem;
	}
	public String getDescricao() {
		return descricao;
	}
	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}
	
	
	
	
	
	

}

nannytruffas_back/src/br/com/nannytruffas/model/Ingredientes.java
package br.com.nannytruffas.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class Ingredientes {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)//auto incremente
	@Column(name="ing_id")
	private Integer id;
	private String nome;
	private Integer quantidade;
	
	
	@ManyToOne
	private UnidadeMedida unidade = new UnidadeMedida();
	
	
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public Integer getQuantidade() {
		return quantidade;
	}
	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}
	public UnidadeMedida getUnidade() {
		return unidade;
	}
	public void setUnidade(UnidadeMedida unidade) {
		this.unidade = unidade;
	}
	
	
}

nannytruffas_back/src/br/com/nannytruffas/model/Login.java
package br.com.nannytruffas.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


@Entity
public class Login {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)//auto incremente
	private Integer id;
	private String usuario;
	private String senha;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getUsuario() {
		return usuario;
	}
	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}
	public String getSenha() {
		return senha;
	}
	public void setSenha(String senha) {
		this.senha = senha;
	}
	
	
	

}

nannytruffas_back/src/br/com/nannytruffas/model/Produto.java
package br.com.nannytruffas.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

@Entity
public class Produto {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)//auto incremente
	@Column(name="prod_id")
	private Integer id;
	private String nome;
	private Double preco_unitario;
	private Double preco_cento;
	
	@ManyToOne
	private TipoProduto Tipo = new TipoProduto();

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Double getPreco_unitario() {
		return preco_unitario;
	}

	public void setPreco_unitario(Double preco_unitario) {
		this.preco_unitario = preco_unitario;
	}

	public Double getPreco_cento() {
		return preco_cento;
	}

	public void setPreco_cento(Double preco_cento) {
		this.preco_cento = preco_cento;
	}

	public TipoProduto getTipo() {
		return Tipo;
	}

	public void setTipo(TipoProduto tipo) {
		Tipo = tipo;
	}
	
	
}

nannytruffas_back/src/br/com/nannytruffas/controller/ComprasController.java
package br.com.nannytruffas.controller;

import java.util.LinkedList;
import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import br.com.nannytruffas.dao.Dao;
import br.com.nannytruffas.model.Compra;
import br.com.nannytruffas.model.Ingredientes;

@ManagedBean
@ViewScoped
public class ComprasController {
	private Compra compra = new Compra();
	private List<Integer> ingredientes = new LinkedList<Integer>();
	public List<Integer> getIngredientes() {
		return ingredientes;
	}

	public void setIngredientes(List<Integer> ingredientes) {
		this.ingredientes = ingredientes;
	}

	public List<Ingredientes> getTodosIngredientes() {
		return new Dao<Ingredientes>(Ingredientes.class).listaTodos();
	}
	
	public List<Compra> getTodasCompras() {
		return new Dao<Compra>(Compra.class).listaTodos();
	}

	public void gravar() {
		Dao<Compra> dao = new Dao<Compra>(Compra.class);

		if (compra.getId() == null) {
			dao.adiciona(compra);
		} else
			dao.atualiza(compra);

		compra = new Compra();

	}

	public Compra getCompra() {
		return compra;
	}

	public void setCompra(Compra compra) {
		this.compra = compra;
	}

	public void atualizar(Compra c) {
		this.compra = c;
	}

	public void remover(Compra c) {
		new Dao<Compra>(Compra.class).remove(c.getId());
	}
	
	public String compras(){
		Double total = 0.0;
		List<Compra> compra  = getTodasCompras();
		
		for (Compra c : compra) {
			total+=c.getPreco_total();
		}
		
		return String.format("%.2f", total);
	}

}

nannytruffas_back/src/br/com/nannytruffas/controller/FeedbackController.java
package br.com.nannytruffas.controller;

import java.util.List;

import br.com.nannytruffas.dao.Dao;
import br.com.nannytruffas.model.Feedback;

public class FeedbackController {
	public List<Feedback> getTodosFeedbacks(){
		return new Dao<Feedback>(Feedback.class).listaTodos();
	}
}

nannytruffas_back/src/br/com/nannytruffas/controller/ImagensController.java
package br.com.nannytruffas.controller;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import br.com.nannytruffas.dao.Dao;
import br.com.nannytruffas.model.Imagens;


@ManagedBean
@ViewScoped
public class ImagensController {
	
	
	private Imagens imagem =  new Imagens();

	public Imagens getImagem() {
		return imagem;
	}

	public void setImagem(Imagens imagem) {
		this.imagem = imagem;
	}
	
	public void gravar(){
		Dao<Imagens> dao = new Dao<Imagens>(Imagens.class);
		
		if (imagem.getId() == null)
			dao.adiciona(imagem);
		else
			dao.atualiza(imagem);
		
		imagem = new Imagens();
	}
	
	public List<Imagens> getTodasImagens(){
		return new Dao<Imagens>(Imagens.class).listaTodos();
	}
	
	public void carregar(Imagens imagem){
		this.imagem = imagem;
	}
	
	public void remover(Imagens imagem){
		new Dao<Imagens>(Imagens.class).remove(imagem.getId());
	}
	

}

nannytruffas_back/src/br/com/nannytruffas/controller/IngredientesController.java
package br.com.nannytruffas.controller;

import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.com.nannytruffas.dao.Dao;
import br.com.nannytruffas.model.Ingredientes;
import br.com.nannytruffas.model.UnidadeMedida;


@ManagedBean
@ViewScoped
public class IngredientesController {
	
	private Ingredientes ingrediente = new Ingredientes();
	private Integer unidmedidaId;
	
	public Integer getUnidmedidaId() {
		return unidmedidaId;
	}
	public void setUnidmedidaId(Integer unidmedidaId) {
		this.unidmedidaId = unidmedidaId;
	}
	public Ingredientes getIngrediente() {
		return ingrediente;
	}
	public void setIngrediente(Ingredientes ingrediente) {
		this.ingrediente = ingrediente;
	}
	public Integer getUnidmedida() {
		return unidmedidaId;
	}
	public void setUnidmedida(Integer unidmedida) {
		this.unidmedidaId = unidmedida;
	}
	
	
	public List<UnidadeMedida> getTodasUnidades(){
		return new Dao<UnidadeMedida>(UnidadeMedida.class).listaTodos();
	}

	
	public void gravar(){
		Dao<Ingredientes> dao = new Dao<Ingredientes>(Ingredientes.class);
		
		if ( unidmedidaId == null || unidmedidaId == 0){
			FacesContext.getCurrentInstance().addMessage(
					"unidmedida",
					new FacesMessage("Selecione a unidade de medida"));
			return;
		}
		
		UnidadeMedida u = new Dao<UnidadeMedida>(UnidadeMedida.class).listaPorId(unidmedidaId);
		ingrediente.setUnidade(u);
		
		if (ingrediente.getId() == null)
			dao.adiciona(ingrediente);
		else 
			dao.atualiza(ingrediente);
		
		ingrediente = new Ingredientes();
		unidmedidaId = null;
	}
	
	public List<Ingredientes> getTodosIngredientes(){
		return new Dao<Ingredientes>(Ingredientes.class).listaTodos();
	}

	public void remover(Ingredientes i){
		new Dao<Ingredientes>(Ingredientes.class).remove(i.getId());
	}
	
	
	public void carregar(Ingredientes i){
		this.ingrediente = i;
		unidmedidaId = ingrediente.getUnidade().getId();
	}
	
	
}

nannytruffas_back/src/br/com/nannytruffas/controller/LoginController.java
package br.com.nannytruffas.controller;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;

import br.com.nannytruffas.dao.LoginDao;
import br.com.nannytruffas.model.Login;


@ManagedBean
@ViewScoped
public class LoginController {
	private Login login = new Login();

	public Login getLogin() {
		return login;
	}

	public void setLogin(Login login) {
		this.login = login;
	}
	
	public String logar() {

		login = new LoginDao().buscarUsuario(login.getUsuario(),login.getSenha());

		FacesContext context = FacesContext.getCurrentInstance();

		if (this.login != null) {
			context.getExternalContext().getSessionMap().put("usuarioLogado", login);
			return "dashboard?faces-redirect=true";
			
		} else {
			context.getExternalContext().getFlash().setKeepMessages(true);
			context.addMessage(null, new FacesMessage("Usuario e/ou senha incorretos"));
			
			return "login?faces-redirect=true";
		}
	}

	

}

nannytruffas_back/src/br/com/nannytruffas/controller/ProdutoController.java
package br.com.nannytruffas.controller;

import java.util.List;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import br.com.nannytruffas.dao.Dao;
import br.com.nannytruffas.model.Produto;
import br.com.nannytruffas.model.TipoProduto;


@ManagedBean
@ViewScoped
public class ProdutoController {
	private Produto prod = new Produto();
	private Integer categoriaId;
	
	public void gravar(){
		Dao<Produto> dao = new Dao<Produto>(Produto.class);
		
		TipoProduto p = new Dao<TipoProduto>(TipoProduto.class).listaPorId(categoriaId);
		prod.setTipo(p);
		
		if(prod.getId() == null){
			dao.adiciona(prod);
		}
		else
			dao.atualiza(prod);
		
		prod = new Produto();
		categoriaId = null;
	}
	
	public Integer getCategoriaId() {
		return categoriaId;
	}

	public void setCategoriaId(Integer categoriaId) {
		this.categoriaId = categoriaId;
	}

	public void atualiza(Produto p){
		System.out.println(p);
		this.prod = p;
	}
	
	public void remover(Produto p) {
		 new Dao<Produto>(Produto.class).remove(p.getId());
	}

	
	public Produto getProd() {
		return prod;
	}

	public void setProd(Produto prod) {
		this.prod = prod;
	}

	public List<TipoProduto> getTodosTipoProduto(){
		return new Dao<TipoProduto>(TipoProduto.class).listaTodos();
	}
	
	public List<Produto> getTodosProdutos(){
		return new Dao<Produto>(Produto.class).listaTodos();
	}
	
	
}

nannytruffas_back/WebContent/compras.xhtml
<?xml version="1.0" ?>
<!DOCTYPE html>


<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
	<ui:include src="head.xhtml" />
</h:head>

<h:body>

	<div class="wrapper">
		<ui:include src="menu.xhtml" />
		<div class="main-panel">
			<ui:include src="menu2.xhtml" />
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="card">
							<div class="header">
								<h4 class="title">Compra</h4>
							</div>
							<div class="content">
								<h:form>
									<div class="row">
										<div class="col-md-6">
											<h:outputLabel value="Data :" for="data" />
											<h:inputText id="data"
												value="#{comprasController.compra.data.time}"
												class="form-control">
												<f:convertDateTime pattern="yyyy-MM-dd"
													timeZone="America/Sao_Paulo" />
												<f:passThroughAttribute name="type" value="date" />
											</h:inputText>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label>Valor</label>
												<h:inputText class="form-control" type="text"
													value="#{comprasController.compra.preco_total}">

												</h:inputText>
											</div>
										</div>

									</div>
									
									<div class="row">
										
										<div class="col-md-3">
											<label>Ingredientes da Compra</label>
											<h:selectManyMenu id="tipo" class="form-control custom-select"
												value="#{comprasController.ingredientes}">
												<f:selectItems value="#{comprasController.todosIngredientes}"
													var="ing" itemLabel="#{ing.nome}" itemValue="#{ing.id}" />
											</h:selectManyMenu>
										</div>
								
									</div>

									<h:commandButton value="Gravar"
										class="btn btn-success btn-fill pull-right btn-sm"
										action="#{comprasController.gravar}">

									</h:commandButton>
									<div class="clearfix"></div>

								</h:form>
							</div>

						</div>

					</div>
					<div class="row">
						<div class="card">
							<div class="header">
								<h4 class="title">Compras</h4>
							</div>
							<div class="card-body">
								<div class="content table-responsive table-full-width">
									<h:form>
										<h:dataTable var="c"
											class="table table-hover table-striped table-responsive-sm"
											value="#{comprasController.todasCompras}">
											<h:column>
												<f:facet name="header">Data</f:facet>
												<h:outputText value="#{c.data.time}">
													<f:convertDateTime pattern="dd/MM/yyyy"
														timeZone="America/Sao_Paulo" />
												</h:outputText>
											</h:column>

											<h:column>
												<f:facet name="header">Valor</f:facet>
												<h:outputText value="#{c.preco_total}"></h:outputText>
											</h:column>
											<h:column>
												<f:facet name="header">Atualizar</f:facet>
												<h:commandButton value="Atualiza"
													action="#{comprasController.atualizar(c)}"
													class="btn btn-primary btn-fill btn-sm" />
											</h:column>
											<h:column>
												<f:facet name="header">Excluir</f:facet>
												<h:commandButton value="Excluir"
													action="#{comprasController.remover(c)}"
													class="btn btn-danger btn-fill btn-sm" />
											</h:column>

										</h:dataTable>
									</h:form>
								</div>
								<div class="row content">
									<div class="header">
										<h5 class="title pull-right">
											Total : R$ <h:outputText value="#{comprasController.compras()}"></h:outputText>
											</h5>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<ui:include src="footer.xhtml" />
		</div>

	</div>
</h:body>

</html>

nannytruffas_back/WebContent/dashboard.xhtml
<?xml version="1.0" ?>
<!DOCTYPE html>


<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
	<ui:include src="head.xhtml" />

</h:head>
<h:body>

	<div class="wrapper">
		<ui:include src="menu.xhtml" />
		<div class="main-panel">
			<ui:include src="menu2.xhtml" />
			<div class="content">
				<div class="container-fluid"></div>
			</div>
			<ui:include src="footer.xhtml" />
		</div>
	</div>


</h:body>



</html>

nannytruffas_back/WebContent/ingredientes.xhtml
<?xml version="1.0" ?>
<!DOCTYPE html>


<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
	<ui:include src="head.xhtml" />
</h:head>

<h:body>

	<div class="wrapper">
		<ui:include src="menu.xhtml" />
		<div class="main-panel">
			<ui:include src="menu2.xhtml" />
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						<div class="card">
							<div class="header">
								<h4 class="title">Ingrediente</h4>
							</div>
							<div class="content">
								<h:form>
									<div class="row">
										<div class="col-md-6">
											<h:outputLabel value="Nome" for="nome" />
											<h:inputText id="nome" class="form-control"
												value="#{ingredientesController.ingrediente.nome}"
												required="true" requiredMessage="Nome obrigatório.">
											</h:inputText>
											<f:passThroughAttribute name="placeholder"
												value="Digite o Nome" />
										</div>


										<div class="col-md-3">
											<h:outputLabel value="quantidade" for="quantidade" />
											<h:inputText id="quantidade" class="form-control"
												value="#{ingredientesController.ingrediente.quantidade}"
												required="true" requiredMessage="Quantidade obrigatória.">
											</h:inputText>
											<f:passThroughAttribute name="placeholder"
												value="Digite a quantidade" />
										</div>

										<div class="col-md-3">
											<div class="form-group">
												<h:outputLabel value="unidade" for="unidade" />
												<h:selectOneMenu id="unidade"
													value="#{ingredientesController.unidmedidaId}"
													class="form-control custom-select">
													<f:selectItem itemLabel="Selecionar"
														noSelectionOption="true" />
													<f:selectItems
														value="#{ingredientesController.todasUnidades}"
														var="unidade" itemLabel="#{unidade.sigla}"
														itemValue="#{unidade.id}" />
												</h:selectOneMenu>
											</div>
										</div>
									</div>
									
										<h:commandButton value="Gravar"
											class="btn btn-success btn-fill pull-right btn-sm"
											action="#{ingredientesController.gravar}">

										</h:commandButton>
										<div class="clearfix"></div>
									
								</h:form>
							</div>

						</div>

					</div>
					<div class="row">
						<div class="card">
							<div class="header">
								<h4 class="title">Ingredientes</h4>
							</div>
							<div class="card-body">
								<div class="content table-responsive table-full-width">
								<h:form>
									<h:dataTable var="i"
										class="table table-hover table-striped table-responsive-sm"
										value="#{ingredientesController.todosIngredientes}">
										<h:column>
											<f:facet name="header">Nome</f:facet>
											<h:outputText value="#{i.nome}" />
										</h:column>

										<h:column>
											<f:facet name="header">quantidade</f:facet>
											<h:outputText value="#{i.quantidade}"></h:outputText>
										</h:column>
										<h:column>
											<f:facet name="header">Unidade</f:facet>
											<h:outputText value="#{i.unidade.descricao}"></h:outputText>
										</h:column>

										<h:column>
											<f:facet name="header">Atualizar</f:facet>
											<h:commandButton value="Atualiza"
												action="#{ingredientesController.carregar(i)}"
												class="btn btn-primary btn-fill btn-sm" />
										</h:column>
										<h:column>
											<f:facet name="header">Excluir</f:facet>
											<h:commandButton value="Excluir"
												action="#{ingredientesController.remover(i)}"
												class="btn btn-danger btn-fill btn-sm" />
										</h:column>

									</h:dataTable>
									</h:form>
								</div>

							</div>
						</div>
					</div>
				</div>
			</div>
			<ui:include src="footer.xhtml" />
		</div>

	</div>
</h:body>

</html>

nannytruffas_back/WebContent/produtos.xhtml
<?xml version="1.0" ?>
<!DOCTYPE html>


<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
<h:head>
	<ui:include src="head.xhtml" />
</h:head>

<h:body>

	<div class="wrapper">
		<ui:include src="menu.xhtml" />
		<div class="main-panel">
			<ui:include src="menu2.xhtml" />
			<div class="content">

				<div class="container-fluid">
					<div class="row">
						<div class="card">
							<div class="header">
								<h4 class="title">Produto</h4>
							</div>
							<div class="content">
								<h:form>
									<div class="row">
										<div class="col-md-6">
											<div class="form-group">
												<label>Nome</label>
												<h:inputText class="form-control" type="text"
													value="#{produtoController.prod.nome}"></h:inputText>
											</div>
										</div>
										<div class="col-md-3">
											<div class="form-group">
												<label>Preço unitario</label>
												<h:inputText class="form-control" type="text"
													value="#{produtoController.prod.preco_unitario}">
													
												</h:inputText>
											</div>
										</div>
										<div class="col-md-3">
											<div class="form-group">
												<label>Preço por cento</label>
												<h:inputText class="form-control" type="text"
													value="#{produtoController.prod.preco_cento}">
													
												</h:inputText>
											</div>
										</div>
									</div>

									<div class="row">
										<div class="col-md-3">
											<label>Tipo do produto</label>
											<h:selectOneMenu id="tipo" class="form-control custom-select"
												value="#{produtoController.categoriaId}">
												<f:selectItem
													itemLabel="#{produtoController.prod.tipo.nome}"
													noSelectionOption="false" />
												<f:selectItems value="#{produtoController.todosTipoProduto}"
													var="tipo" itemLabel="#{tipo.nome}" itemValue="#{tipo.id}" />
											</h:selectOneMenu>
										</div>
									</div>

									<h:commandButton class="btn btn-success btn-fill pull-right btn-sm"
										type="submit" action="#{produtoController.gravar}" value="#{(produtoController.prod.id == null)?'Cadastrar':'Atualizar'}"></h:commandButton>
									<div class="clearfix"></div>
									
								</h:form>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="card">
							<div class="header">
								<h4 class="title">Produtos</h4>
							</div>
							<div class="card-body">
								<div class="content table-responsive table-full-width">
								<h:form>
									<h:dataTable var="p"
										class="table table-hover table-striped table-responsive-sm"
										value="#{produtoController.todosProdutos}">
										<h:column>
											<f:facet name="header">Nome</f:facet>
											<h:outputText value="#{p.nome}" />
										</h:column>

										<h:column>
											<f:facet name="header">Preço unitário</f:facet>
											<h:outputText value="#{p.preco_unitario}"></h:outputText>
										</h:column>
										<h:column>
											<f:facet name="header">Preço por cento</f:facet>
											<h:outputText value="#{p.preco_cento}"></h:outputText>
										</h:column>

										<h:column>
											<f:facet name="header">Tipo</f:facet>
											<h:outputText value="#{p.tipo.nome}"></h:outputText>
										</h:column>

										<h:column>
											<f:facet name="header">Atualizar</f:facet>
											<h:commandButton value="Atualiza"
												action="#{produtoController.atualiza(p)}"
												class="btn btn-primary btn-fill btn-sm" />
										</h:column>
										<h:column>
											<f:facet name="header">Excluir</f:facet>
											<h:commandButton value="Excluir"
												action="#{produtoController.remover(p)}"
												class="btn btn-danger btn-fill btn-sm" />
										</h:column>

									</h:dataTable>
									</h:form>
								</div>

							</div>
						</div>
					</div>

				</div>
			</div>
			<ui:include src="footer.xhtml" />
		</div>
	</div>


</h:body>

</html>